const ACCOUNTS=[{id:'account-1',name:'บัญชีหลัก',color:'#6d5dfc',host:'api.vmoscloud.com',accessKey:'B4cC••••••••nq96P'},{id:'account-2',name:'บัญชีที่ 2',color:'#22c55e',host:'api.vmoscloud.com',accessKey:'RMAc••••••••3bQ4'}];
const PATHS={list:['/vcpcloud/api/padApi/userPadList','/vcpcloud/api/padApi/padDetail','/vcpcloud/api/padApi/infos'],restart:'/vcpcloud/api/padApi/restart',reset:'/vcpcloud/api/padApi/reset',replace:'/vcpcloud/api/padApi/replacePad',language:'/vcpcloud/api/padApi/updateLanguage',timezone:'/vcpcloud/api/padApi/updateTimeZone',rename:'/vcpcloud/api/padApi/updatePadName',preview:'/vcpcloud/api/padApi/getLongGenerateUrl'};
const LANGUAGES=[['ไทย','th','TH'],['English','en','US'],['จีน','zh','CN'],['เวียดนาม','vi','VN'],['อินโดนีเซีย','id','ID'],['โปรตุเกส','pt','BR'],['สเปน','es','ES'],['ญี่ปุ่น','ja','JP'],['เกาหลี','ko','KR']];
const TIMEZONES=[['กรุงเทพฯ','Asia/Bangkok'],['จาการ์ตา','Asia/Jakarta'],['โฮจิมินห์','Asia/Ho_Chi_Minh'],['สิงคโปร์','Asia/Singapore'],['มะนิลา','Asia/Manila'],['โตเกียว','Asia/Tokyo'],['โซล','Asia/Seoul'],['ลอนดอน','Europe/London'],['นิวยอร์ก','America/New_York'],['ลอสแอนเจลิส','America/Los_Angeles']];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],key=d=>`${d.accountId}:${d.padCode}`;
const saved=JSON.parse(localStorage.getItem('vmos-groups')||'{"groups":[],"assignments":{}}');
const state={devices:[],logs:JSON.parse(localStorage.getItem('vmos-logs')||'[]'),groups:saved.groups||[],assignments:saved.assignments||{},selected:new Set(),loading:false,viewMode:localStorage.getItem('vmos-view')||'grid'};
async function api(account,path,body={}){let response;try{response=await fetch('/api/vmos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accountId:account.id,path,body})})}catch(e){e.isNetwork=true;throw e}const text=await response.text();let data;try{data=JSON.parse(text)}catch{throw new Error(`ตัวกลาง API ตอบกลับผิดรูปแบบ (${response.status})`)}if(!response.ok||data.code!==200)throw new Error(data.msg||data.error||`API Error ${data.code||response.status}`);return data}
function normalize(raw,a){return{accountId:a.id,accountName:a.name,accountColor:a.color,padCode:raw.padCode||raw.code||'-',name:raw.padName||raw.name||raw.padCode||'Cloud Phone',online:Number(raw.online??raw.status??0)===1,cvmStatus:Number(raw.cvmStatus??raw.padStatus??0),ip:raw.padIp||raw.deviceIp||raw.padIpV4||'-',model:raw.configName||raw.goodName||raw.androidVersion||'-',expires:raw.signExpirationTime||raw.expireTime||'-',preview:raw.screenshotLink||raw.screenshotUrl||''}}
function extractList(data){if(Array.isArray(data))return data;for(const k of['list','records','rows','data','padList'])if(Array.isArray(data?.[k]))return data[k];return[]}
async function loadAccount(a){let last;for(const path of PATHS.list)try{const res=await api(a,path,path.endsWith('/padDetail')?{rows:1000}:{});return extractList(res.data).map(x=>normalize(x,a))}catch(e){last=e}throw last}
async function refresh(){if(state.loading)return;state.loading=true;$('#refreshBtn').disabled=true;$('#refreshBtn').textContent='↻ กำลังโหลด';const results=await Promise.allSettled(ACCOUNTS.map(loadAccount));state.devices=results.flatMap(x=>x.status==='fulfilled'?x.value:[]);const failed=results.filter(x=>x.status==='rejected');failed.forEach(x=>log('เชื่อมต่อบัญชีไม่สำเร็จ',x.reason.message,'error'));toast(failed.length?`เชื่อมต่อไม่สำเร็จ ${failed.length} บัญชี`:`โหลด ${state.devices.length} เครื่องแล้ว`,failed.length?'error':'success');$('#apiState').textContent=failed.length?'เชื่อมต่อบางบัญชี':'เชื่อมต่อแล้ว';$('#lastSync').textContent='อัปเดต '+new Date().toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'});state.loading=false;$('#refreshBtn').disabled=false;$('#refreshBtn').textContent='↻ รีเฟรช';render()}
function groupName(d){return state.groups.find(g=>g.id===state.assignments[key(d)])?.name||''}function saveGroups(){localStorage.setItem('vmos-groups',JSON.stringify({groups:state.groups,assignments:state.assignments}))}
function statusOf(d){if([14,104].includes(d.cvmStatus))return'abnormal';return d.online?'online':'offline'}function statusText(d){return statusOf(d)==='online'?'ออนไลน์':statusOf(d)==='abnormal'?'ผิดปกติ':'ออฟไลน์'}
function filtered(){const q=$('#searchInput').value.trim().toLowerCase(),acc=$('#accountFilter').value,st=$('#statusFilter').value,g=$('#groupFilter').value,sort=$('#sortSelect').value;const out=state.devices.filter(d=>(acc==='all'||d.accountId===acc)&&(st==='all'||statusOf(d)===st)&&(g==='all'||(g==='ungrouped'?!state.assignments[key(d)]:state.assignments[key(d)]===g))&&(!q||`${d.name} ${d.padCode}`.toLowerCase().includes(q)));return out.sort((a,b)=>sort==='name-desc'?b.name.localeCompare(a.name,undefined,{numeric:true}):sort==='code-asc'?a.padCode.localeCompare(b.padCode,undefined,{numeric:true}):a.name.localeCompare(b.name,undefined,{numeric:true}))}
function render(){renderStats();renderGroups();renderDevices();renderAccounts();renderLogs();renderBulk();renderQuota()}
function renderStats(){const total=state.devices.length,on=state.devices.filter(d=>statusOf(d)==='online').length,off=state.devices.filter(d=>statusOf(d)==='offline').length,bad=state.devices.filter(d=>statusOf(d)==='abnormal').length;$('#stats').innerHTML=[['เครื่องทั้งหมด',total,'▦'],['ออนไลน์',on,'●'],['ออฟไลน์',off,'○'],['ผิดปกติ',bad,'!']].map(([l,v,i])=>`<div class="stat-card"><span class="stat-icon">${i}</span><div class="stat-label">${l}</div><div class="stat-value">${v} <small>เครื่อง</small></div></div>`).join('')}
function renderGroups(){const cur=$('#groupFilter').value;$('#groupFilter').innerHTML='<option value="all">ทุกกลุ่มงาน</option><option value="ungrouped">ยังไม่มีกลุ่ม</option>'+state.groups.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('');$('#groupFilter').value=[...$('#groupFilter').options].some(o=>o.value===cur)?cur:'all'}
function renderDevices(){const list=filtered(),grid=$('#deviceGrid');grid.className='device-grid '+(state.viewMode==='list'?'list':'');grid.innerHTML=list.map(d=>{const k=key(d),group=groupName(d);return`<article class="device-card ${state.selected.has(k)?'selected':''}"><div class="device-preview">${d.preview?`<img src="${esc(d.preview)}" onerror="this.remove()">`:'<div class="phone-placeholder">▯</div>'}<span class="status-pill ${statusOf(d)}"><i></i>${statusText(d)}</span><span class="account-badge" style="background:${d.accountColor}">${esc(d.accountName)}</span><input class="device-check" type="checkbox" ${state.selected.has(k)?'checked':''} onchange="toggleDevice('${k}')"></div><div class="device-body">${group?`<span class="group-badge">▰ ${esc(group)}</span>`:''}<div class="device-title"><h3>${esc(d.name)}</h3><button onclick="openDevice('${d.accountId}','${d.padCode}')">•••</button></div><div class="device-code">${esc(d.padCode)}</div><div class="device-meta"><span>IP ADDRESS<b>${esc(d.ip)}</b></span><span>รุ่นเครื่อง<b>${esc(d.model)}</b></span><span>หมดอายุ<b>${esc(d.expires)}</b></span><span>สถานะระบบ<b>${d.cvmStatus||'-'}</b></span></div><div class="device-actions"><button class="control-btn" onclick="openDevice('${d.accountId}','${d.padCode}')">จัดการเครื่อง</button><button onclick="singleAction('restart','${d.accountId}','${d.padCode}')">↻</button><button onclick="refreshPreview('${d.accountId}','${d.padCode}')">▧</button></div></div></article>`}).join('');$('#emptyState').classList.toggle('hidden',!!list.length)}
function renderAccounts(){const counts=Object.fromEntries(ACCOUNTS.map(a=>[a.id,state.devices.filter(d=>d.accountId===a.id).length]));$('#accountList').innerHTML='<div class="account-title">บัญชีของฉัน</div>'+ACCOUNTS.map(a=>`<div class="account-row"><i class="account-dot" style="background:${a.color}"></i>${a.name}<small>${counts[a.id]} เครื่อง</small></div>`).join('');$('#settingsAccounts').innerHTML=ACCOUNTS.map(a=>`<div class="settings-account"><b>${a.name}</b><div>Host: <code>${a.host}</code><br>Access Key: <code>${a.accessKey}</code></div></div>`).join('')}
function renderLogs(){const el=$('#activityList');el.innerHTML=state.logs.length?state.logs.map(x=>`<div class="activity-item ${x.type}"><i></i><div><b>${esc(x.title)}</b><br><small>${esc(x.detail)}</small></div><small>${new Date(x.time).toLocaleString('th-TH')}</small></div>`).join(''):'<div class="empty"><div>◷</div><h3>ยังไม่มีประวัติ</h3></div>'}
function renderBulk(){$('#selectedCount').textContent=state.selected.size;$('#bulkBar').classList.toggle('hidden',!state.selected.size)}
function quota(){const day=new Date().toLocaleDateString('en-CA'),q=JSON.parse(localStorage.getItem('vmos-replace-quota')||'{}');return{day,used:q.day===day?(q.used||0):0}}function renderQuota(){const q=quota();$('#quotaText').textContent=`โควตาเปลี่ยนเครื่องวันนี้: ${Math.max(0,500-q.used)}/500`}
function toggleDevice(k){state.selected.has(k)?state.selected.delete(k):state.selected.add(k);renderDevices();renderBulk()}function selectedDevices(){return state.devices.filter(d=>state.selected.has(key(d)))}function clearSelection(){state.selected.clear();renderDevices();renderBulk()}
function openModal(html){$('#modalContent').innerHTML=html;$('#modalBackdrop').classList.remove('hidden')}function closeModal(){$('#modalBackdrop').classList.add('hidden')}
function manageGroups(){openModal(`<h2>จัดการกลุ่มงาน</h2><p>สร้างกลุ่มเพื่อเลือกและสั่งงานหลายเครื่องพร้อมกัน</p><div class="form-group"><label>ชื่อกลุ่มใหม่</label><input id="groupNameInput" placeholder="เช่น งาน Facebook ชุด A"></div><button class="primary-btn" onclick="createGroup()">สร้างกลุ่ม</button><div>${state.groups.map(g=>`<div class="group-row"><span>${esc(g.name)}</span><button onclick="deleteGroup('${g.id}')">ลบ</button></div>`).join('')||'<p>ยังไม่มีกลุ่มงาน</p>'}</div>`)}
function createGroup(){const name=$('#groupNameInput').value.trim();if(!name)return;state.groups.push({id:'g'+Date.now(),name});saveGroups();render();manageGroups()}function deleteGroup(id){if(!confirm('ลบกลุ่มนี้หรือไม่? เครื่องจะไม่ถูกลบ'))return;state.groups=state.groups.filter(g=>g.id!==id);Object.keys(state.assignments).forEach(k=>{if(state.assignments[k]===id)delete state.assignments[k]});saveGroups();render();manageGroups()}
function groupChoice(){if(!state.groups.length)return manageGroups();openModal(`<h2>ย้าย ${state.selected.size} เครื่องเข้ากลุ่ม</h2><div class="choice-grid"><button onclick="assignGroup('')">ไม่มีกลุ่ม</button>${state.groups.map(g=>`<button onclick="assignGroup('${g.id}')">${esc(g.name)}</button>`).join('')}</div>`)}function assignGroup(id){state.selected.forEach(k=>id?state.assignments[k]=id:delete state.assignments[k]);saveGroups();closeModal();render();toast('บันทึกกลุ่มแล้ว')}
function choiceModal(type){const items=type==='language'?LANGUAGES:TIMEZONES;openModal(`<h2>${type==='language'?'เปลี่ยนภาษา':'เปลี่ยนเขตเวลา'} ${state.selected.size} เครื่อง</h2><div class="choice-grid">${items.map(x=>`<button onclick='runChoice(${JSON.stringify(type)},${JSON.stringify(x)})'>${esc(x[0])}</button>`).join('')}</div>`)}
async function runChoice(type,item){closeModal();await runBulk(type,type==='language'?{language:item[1],country:item[2]}:{timeZone:item[1]})}
async function singleAction(action,id,code){state.selected=new Set([`${id}:${code}`]);await bulkAction(action)}
async function bulkAction(action){if(action==='group')return groupChoice();if(action==='language'||action==='timezone')return choiceModal(action);const n=state.selected.size,labels={restart:'รีสตาร์ต',reset:'เริ่มต้นใหม่และล้างข้อมูล',replace:'เปลี่ยนเครื่องและล้างข้อมูล'};if(!confirm(`${labels[action]} ${n} เครื่อง ใช่หรือไม่?${['reset','replace'].includes(action)?' ข้อมูลในเครื่องจะถูกลบทั้งหมด':''}`))return;if(action==='replace'&&n>500-quota().used)return toast('จำนวนที่เลือกเกินโควตาที่เหลือวันนี้','error');await runBulk(action,{})}
async function runBulk(action,extra){const devices=selectedDevices(),groups=Object.groupBy?Object.groupBy(devices,d=>d.accountId):devices.reduce((o,d)=>((o[d.accountId]||=[]).push(d),o),{}),path=PATHS[action];let ok=0,fail=0;if(action==='replace'){for(let i=0;i<devices.length;i++){const d=devices[i],a=ACCOUNTS.find(x=>x.id===d.accountId);$('#apiState').textContent=`กำลังเปลี่ยน ${i+1}/${devices.length}`;try{const res=await api(a,path,{padCodes:[d.padCode],countryCode:'SG',wipeData:true,...extra}),task=Array.isArray(res.data)?res.data[0]:res.data;if(task?.taskStatus===-1)throw new Error('มีคำสั่งเดิมกำลังทำงานอยู่');ok++;log('เปลี่ยนเครื่องสำเร็จ',`${d.padCode} · ${a.name}`)}catch(e){fail++;log(`เปลี่ยนเครื่อง ${d.padCode} ไม่สำเร็จ`,e.message,'error')}if(i<devices.length-1)await new Promise(r=>setTimeout(r,450))}}else{for(const[id,list]of Object.entries(groups))try{await api(ACCOUNTS.find(a=>a.id===id),path,{padCodes:list.map(d=>d.padCode),...extra});ok+=list.length;log(`${action} สำเร็จ`,`${list.length} เครื่อง · ${ACCOUNTS.find(a=>a.id===id).name}`)}catch(e){fail+=list.length;log(`${action} ไม่สำเร็จ`,e.message,'error')}}if(action==='replace'&&ok){const q=quota();localStorage.setItem('vmos-replace-quota',JSON.stringify({day:q.day,used:q.used+ok}))}$('#apiState').textContent='เชื่อมต่อแล้ว';toast(`สำเร็จ ${ok} เครื่อง${fail?` · ไม่สำเร็จ ${fail}`:''}`,fail?'error':'success');clearSelection();renderQuota();setTimeout(refresh,1800)}
function openDevice(id,code){const d=state.devices.find(x=>x.accountId===id&&x.padCode===code);if(!d)return;openModal(`<h2>${esc(d.name)}</h2><p>${d.padCode} · ${d.accountName}</p><div class="modal-preview">${d.preview?`<img src="${esc(d.preview)}">`:'<span class="phone-placeholder">▯</span>'}</div><div class="modal-actions"><button onclick="singleAction('language','${id}','${code}')">เปลี่ยนภาษา</button><button onclick="singleAction('timezone','${id}','${code}')">เปลี่ยนเขตเวลา</button><button onclick="singleAction('restart','${id}','${code}')">รีสตาร์ต</button><button onclick="singleAction('replace','${id}','${code}')">เปลี่ยนเครื่อง</button><button class="danger" onclick="singleAction('reset','${id}','${code}')">เริ่มต้นใหม่</button><button onclick="showRename('${id}','${code}')">เปลี่ยนชื่อ</button></div><div id="modalResult"></div>`)}
async function refreshPreview(id,code){try{const res=await api(ACCOUNTS.find(a=>a.id===id),PATHS.preview,{padCodes:[code]}),x=extractList(res.data)[0]||res.data||{},url=x.url||x.generateUrl||x.screenshotLink||x.longGenerateUrl;if(!url)throw Error('API ไม่ส่ง URL รูปภาพ');state.devices.find(d=>d.accountId===id&&d.padCode===code).preview=url;renderDevices();toast('อัปเดตภาพแล้ว')}catch(e){toast(e.message,'error')}}
function showRename(id,code){const d=state.devices.find(x=>x.accountId===id&&x.padCode===code);$('#modalResult').innerHTML=`<div class="form-group"><label>ชื่อใหม่</label><input id="newName" value="${esc(d.name)}"></div><button class="primary-btn" onclick="renameDevice('${id}','${code}')">บันทึก</button>`}async function renameDevice(id,code){const name=$('#newName').value.trim();if(!name)return;try{await api(ACCOUNTS.find(a=>a.id===id),PATHS.rename,{padCode:code,padName:name});state.devices.find(d=>d.accountId===id&&d.padCode===code).name=name;closeModal();render();toast('เปลี่ยนชื่อแล้ว')}catch(e){toast(e.message,'error')}}
function log(title,detail,type='success'){state.logs.unshift({title,detail,type,time:Date.now()});state.logs=state.logs.slice(0,100);localStorage.setItem('vmos-logs',JSON.stringify(state.logs));renderLogs()}function toast(msg,type='success'){const el=document.createElement('div');el.className='toast '+type;el.textContent=msg;$('#toastStack').append(el);setTimeout(()=>el.remove(),3500)}function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('#refreshBtn').onclick=refresh;['searchInput','accountFilter','groupFilter','statusFilter','sortSelect'].forEach(id=>$('#'+id).addEventListener(id==='searchInput'?'input':'change',renderDevices));$('#manageGroupsBtn').onclick=manageGroups;$('#selectVisibleBtn').onclick=()=>{filtered().forEach(d=>state.selected.add(key(d)));renderDevices();renderBulk()};$('#clearSelection').onclick=clearSelection;$$('[data-bulk]').forEach(b=>b.onclick=()=>bulkAction(b.dataset.bulk));$('#modalClose').onclick=closeModal;$('#modalBackdrop').onclick=e=>{if(e.target===e.currentTarget)closeModal()};$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#clearLogs').onclick=()=>{state.logs=[];localStorage.removeItem('vmos-logs');renderLogs()};$$('.nav-item').forEach(b=>b.onclick=()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.view+'View').classList.add('active');$('#pageTitle').textContent=b.textContent.trim();$('#sidebar').classList.remove('open')});$$('.view-switch button').forEach(b=>b.onclick=()=>{state.viewMode=b.dataset.mode;localStorage.setItem('vmos-view',state.viewMode);renderDevices()});ACCOUNTS.forEach(a=>$('#accountFilter').insertAdjacentHTML('beforeend',`<option value="${a.id}">${a.name}</option>`));render();refresh();
