const ACCOUNTS = [
  { id: 'account-1', name: 'บัญชีหลัก', color: '#6d5dfc', host: 'api.vmoscloud.com', accessKey: 'B4cC••••••••nq96P' },
  { id: 'account-2', name: 'บัญชีที่ 2', color: '#22c55e', host: 'api.vmoscloud.com', accessKey: 'RMAc••••••••3bQ4' }
];

const PATHS = { list:['/vcpcloud/api/padApi/userPadList','/vcpcloud/api/padApi/padDetail','/vcpcloud/api/padApi/infos'], restart:'/vcpcloud/api/padApi/restart', rename:'/vcpcloud/api/padApi/updatePadName', preview:'/vcpcloud/api/padApi/getLongGenerateUrl', token:'/vcpcloud/api/padApi/stsTokenByPadCode', apps:'/vcpcloud/api/padApi/listInstalledApp', stopStream:'/vcpcloud/api/padApi/dissolveRoom' };
const state = { devices:[], logs:JSON.parse(localStorage.getItem('vmos-logs')||'[]'), loading:false, viewMode:localStorage.getItem('vmos-view')||'grid' };
const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];

async function api(account,path,body={}){let response;try{response=await fetch('/api/vmos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accountId:account.id,path,body})})}catch(err){err.isNetwork=true;throw err}const text=await response.text();let data;try{data=JSON.parse(text)}catch{throw new Error(`ตัวกลาง API ตอบกลับผิดรูปแบบ (${response.status})`)}if(!response.ok||data.code!==200)throw new Error(data.msg||data.error||`API Error ${data.code||response.status}`);return data}

function normalize(raw,account){return {accountId:account.id,accountName:account.name,accountColor:account.color,padCode:raw.padCode||raw.code||'-',name:raw.padName||raw.name||raw.padCode||'Cloud Phone',online:Number(raw.online??raw.status??0)===1,cvmStatus:Number(raw.cvmStatus??raw.padStatus??0),ip:raw.padIp||raw.deviceIp||raw.padIpV4||'-',model:raw.configName||raw.goodName||raw.androidVersion||'-',expires:raw.signExpirationTime||raw.expireTime||'-',preview:raw.screenshotLink||raw.screenshotUrl||'',raw}}
function extractList(data){if(Array.isArray(data))return data;for(const key of ['list','records','rows','data','padList'])if(Array.isArray(data?.[key]))return data[key];return []}
async function loadAccount(account){let lastError;for(const path of PATHS.list){try{const body=path.endsWith('/padDetail')?{rows:1000}:{};const res=await api(account,path,body);return extractList(res.data).map(x=>normalize(x,account))}catch(error){lastError=error}}throw lastError||new Error('ไม่พบ Endpoint สำหรับรายการเครื่อง')}
async function refresh(){if(state.loading)return;state.loading=true;$('#refreshBtn').disabled=true;$('#refreshBtn').textContent='↻ กำลังโหลด';$('#corsNotice').classList.add('hidden');const results=await Promise.allSettled(ACCOUNTS.map(loadAccount));state.devices=results.flatMap(r=>r.status==='fulfilled'?r.value:[]);const failed=results.filter(r=>r.status==='rejected');if(failed.length){failed.forEach((r,i)=>log('เชื่อมต่อบัญชีไม่สำเร็จ',r.reason.message,'error'));if(failed.some(r=>r.reason.isNetwork))$('#corsNotice').classList.remove('hidden');toast(`เชื่อมต่อไม่สำเร็จ ${failed.length} บัญชี`,'error')}else{toast(`โหลดเครื่อง ${state.devices.length} เครื่องแล้ว`);$('#apiState').textContent='เชื่อมต่อแล้ว';$('.pulse').style.background='var(--green)'}$('#lastSync').textContent='อัปเดต '+new Date().toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'});state.loading=false;$('#refreshBtn').disabled=false;$('#refreshBtn').textContent='↻ รีเฟรช';render()}

function statusOf(d){if(d.cvmStatus===104||d.cvmStatus===14)return'abnormal';return d.online?'online':'offline'}
function statusText(d){return statusOf(d)==='online'?'ออนไลน์':statusOf(d)==='abnormal'?'ผิดปกติ':'ออฟไลน์'}
function filtered(){const q=$('#searchInput').value.trim().toLowerCase(),acc=$('#accountFilter').value,st=$('#statusFilter').value;return state.devices.filter(d=>(acc==='all'||d.accountId===acc)&&(st==='all'||statusOf(d)===st)&&(!q||`${d.name} ${d.padCode}`.toLowerCase().includes(q)))}
function render(){renderStats();renderDevices();renderAccounts();renderLogs()}
function renderStats(){const total=state.devices.length,on=state.devices.filter(d=>statusOf(d)==='online').length,off=state.devices.filter(d=>statusOf(d)==='offline').length,bad=state.devices.filter(d=>statusOf(d)==='abnormal').length;$('#stats').innerHTML=[['เครื่องทั้งหมด',total,'▦'],['ออนไลน์',on,'●'],['ออฟไลน์',off,'○'],['ผิดปกติ',bad,'!']].map(([l,v,i])=>`<div class="stat-card"><span class="stat-icon">${i}</span><div class="stat-label">${l}</div><div class="stat-value">${v} <small>เครื่อง</small></div></div>`).join('')}
function renderDevices(){const list=filtered(),grid=$('#deviceGrid');grid.className='device-grid '+(state.viewMode==='list'?'list':'');grid.innerHTML=list.map(d=>`<article class="device-card"><div class="device-preview">${d.preview?`<img src="${esc(d.preview)}" alt="ภาพ ${esc(d.name)}" onerror="this.remove()">`:'<div class="phone-placeholder">▯</div>'}<span class="status-pill ${statusOf(d)}"><i></i>${statusText(d)}</span><span class="account-badge" style="background:${d.accountColor}">${esc(d.accountName)}</span></div><div class="device-body"><div class="device-title"><h3>${esc(d.name)}</h3><button onclick="openDevice('${d.accountId}','${d.padCode}')">•••</button></div><div class="device-code">${esc(d.padCode)}</div><div class="device-meta"><span>IP ADDRESS<b>${esc(d.ip)}</b></span><span>รุ่นเครื่อง<b>${esc(d.model)}</b></span><span>หมดอายุ<b>${esc(d.expires)}</b></span><span>สถานะระบบ<b>${d.cvmStatus||'-'}</b></span></div><div class="device-actions"><button class="control-btn" onclick="openDevice('${d.accountId}','${d.padCode}')">ควบคุมเครื่อง</button><button title="รีสตาร์ต" onclick="restartDevice('${d.accountId}','${d.padCode}')">↻</button><button title="ภาพล่าสุด" onclick="refreshPreview('${d.accountId}','${d.padCode}')">▧</button></div></div></article>`).join('');$('#emptyState').classList.toggle('hidden',list.length>0)}
function renderAccounts(){const counts=Object.fromEntries(ACCOUNTS.map(a=>[a.id,state.devices.filter(d=>d.accountId===a.id).length]));$('#accountList').innerHTML='<div class="account-title">บัญชีของฉัน</div>'+ACCOUNTS.map(a=>`<div class="account-row"><i class="account-dot" style="background:${a.color}"></i>${a.name}<small>${counts[a.id]} เครื่อง</small></div>`).join('');$('#settingsAccounts').innerHTML=ACCOUNTS.map(a=>`<div class="settings-account"><b><i class="account-dot" style="display:inline-block;background:${a.color}"></i> ${a.name}</b><div>Host: <code>${a.host}</code><br>Access Key: <code>${a.accessKey}</code><br>Secret: <code>เก็บใน Vercel Function</code></div></div>`).join('')}
function renderLogs(){const el=$('#activityList');el.innerHTML=state.logs.length?state.logs.map(x=>`<div class="activity-item ${x.type}"><i></i><div><b>${esc(x.title)}</b><br><small>${esc(x.detail)}</small></div><small>${new Date(x.time).toLocaleString('th-TH')}</small></div>`).join(''):'<div class="empty"><div>◷</div><h3>ยังไม่มีประวัติ</h3></div>'}
function log(title,detail,type='success'){state.logs.unshift({title,detail,type,time:Date.now()});state.logs=state.logs.slice(0,100);localStorage.setItem('vmos-logs',JSON.stringify(state.logs));renderLogs()}
function account(id){return ACCOUNTS.find(a=>a.id===id)} function device(id,code){return state.devices.find(d=>d.accountId===id&&d.padCode===code)}
async function restartDevice(id,code){if(!confirm(`รีสตาร์ตเครื่อง ${code} ใช่หรือไม่?`))return;try{toast('กำลังส่งคำสั่งรีสตาร์ต...');await api(account(id),PATHS.restart,{padCodes:[code]});log('รีสตาร์ตเครื่อง',`${code} · ${account(id).name}`);toast('ส่งคำสั่งรีสตาร์ตแล้ว')}catch(e){log('รีสตาร์ตไม่สำเร็จ',e.message,'error');toast(e.message,'error')}}
async function refreshPreview(id,code){try{toast('กำลังขอภาพล่าสุด...');const res=await api(account(id),PATHS.preview,{padCodes:[code]});const item=extractList(res.data)[0]||res.data||{};const url=item.url||item.generateUrl||item.screenshotLink||item.longGenerateUrl;if(!url)throw new Error('API ไม่ได้ส่ง URL รูปภาพกลับมา');device(id,code).preview=url;renderDevices();toast('อัปเดตภาพแล้ว')}catch(e){log('โหลดภาพไม่สำเร็จ',e.message,'error');toast(e.message,'error')}}
function openDevice(id,code){const d=device(id,code);if(!d)return;$('#modalContent').innerHTML=`<h2>${esc(d.name)}</h2><p>${esc(d.padCode)} · ${esc(d.accountName)}</p><div class="modal-preview">${d.preview?`<img src="${esc(d.preview)}">`:'<span class="phone-placeholder">▯</span>'}</div><div class="modal-actions"><button onclick="getSdkToken('${id}','${code}')">รับโทเคนควบคุม</button><button onclick="refreshPreview('${id}','${code}')">ภาพหน้าจอล่าสุด</button><button onclick="showRename('${id}','${code}')">เปลี่ยนชื่อ</button><button onclick="restartDevice('${id}','${code}')">รีสตาร์ต</button><button onclick="getApps('${id}','${code}')">ดูแอปที่ติดตั้ง</button><button onclick="stopStream('${id}','${code}')">หยุดสตรีม</button></div><div id="modalResult"></div>`;$('#modalBackdrop').classList.remove('hidden')}
async function modalCall(id,path,body,title){const out=$('#modalResult');out.innerHTML='<p>กำลังโหลด...</p>';try{const res=await api(account(id),path,body);out.innerHTML=`<div class="warning-box" style="background:#0a2730;color:#9ee8f3;border-color:#175061"><b>${title}</b><pre style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(JSON.stringify(res.data,null,2))}</pre></div>`;log(title,JSON.stringify(body))}catch(e){out.innerHTML=`<div class="warning-box">${esc(e.message)}</div>`;log(`${title} ไม่สำเร็จ`,e.message,'error')}}
function getSdkToken(id,code){modalCall(id,PATHS.token,{padCode:code},'SDK Token')} function getApps(id,code){modalCall(id,PATHS.apps,{padCode:code},'รายการแอป')} function stopStream(id,code){modalCall(id,PATHS.stopStream,{padCode:code},'หยุดสตรีม')}
function showRename(id,code){const d=device(id,code);$('#modalResult').innerHTML=`<div class="form-group"><label>ชื่อใหม่</label><input id="newName" value="${esc(d.name)}"></div><button class="primary-btn" onclick="renameDevice('${id}','${code}')">บันทึกชื่อ</button>`;setTimeout(()=>$('#newName')?.focus(),30)}
async function renameDevice(id,code){const name=$('#newName').value.trim();if(!name)return toast('กรุณากรอกชื่อ','error');try{await api(account(id),PATHS.rename,{padCode:code,padName:name});device(id,code).name=name;log('เปลี่ยนชื่อเครื่อง',`${code} → ${name}`);toast('เปลี่ยนชื่อแล้ว');openDevice(id,code);renderDevices()}catch(e){toast(e.message,'error')}}
function toast(message,type='success'){const el=document.createElement('div');el.className='toast '+type;el.textContent=message;$('#toastStack').append(el);setTimeout(()=>el.remove(),3500)} function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

$('#refreshBtn').onclick=refresh;$('#searchInput').oninput=renderDevices;$('#accountFilter').onchange=renderDevices;$('#statusFilter').onchange=renderDevices;$('#modalClose').onclick=()=>$('#modalBackdrop').classList.add('hidden');$('#modalBackdrop').onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.classList.add('hidden')};$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#clearLogs').onclick=()=>{state.logs=[];localStorage.removeItem('vmos-logs');renderLogs()};
$$('.nav-item').forEach(btn=>btn.onclick=()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$$('.view').forEach(x=>x.classList.remove('active'));$('#'+btn.dataset.view+'View').classList.add('active');$('#pageTitle').textContent=btn.textContent.trim();$('#sidebar').classList.remove('open')});
$$('.view-switch button').forEach(btn=>btn.onclick=()=>{state.viewMode=btn.dataset.mode;localStorage.setItem('vmos-view',state.viewMode);$$('.view-switch button').forEach(x=>x.classList.toggle('active',x===btn));renderDevices()});
ACCOUNTS.forEach(a=>$('#accountFilter').insertAdjacentHTML('beforeend',`<option value="${a.id}">${a.name}</option>`));$$('.view-switch button').forEach(x=>x.classList.toggle('active',x.dataset.mode===state.viewMode));render();refresh();
