const AUTO_APPS=[{label:'app-debug',match:'app-debug'},{label:'grab',match:'grab'},{label:'shopee v3-53-31',match:'shopee-v3-53-31'}];
const AUTO_PATHS={files:'/vcpcloud/api/padApi/selectFiles',install:'/vcpcloud/api/padApi/installApp',uploadInstall:'/vcpcloud/api/padApi/uploadFileV3',task:'/vcpcloud/api/padApi/padTaskDetail',fileTask:'/vcpcloud/api/padApi/fileTaskDetail',installed:'/vcpcloud/api/padApi/listInstalledApp'};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function autoInstallEnabled(){return localStorage.getItem('vmos-auto-install')!=='false'}
function normalizeAppName(v){return String(v||'').toLowerCase().replace(/\.apk$/,'').replace(/[\s_]+/g,'-').replace(/-+/g,'-')}
async function getAutoApps(){const res=await api(ACCOUNTS[0],AUTO_PATHS.files,{}),files=Array.isArray(res.data)?res.data:[];const apps=AUTO_APPS.map(want=>{const found=files.find(f=>normalizeAppName(f.appName).includes(want.match));return found?{...found,label:want.label}:null});const missing=AUTO_APPS.filter((_,i)=>!apps[i]).map(x=>x.label);if(missing.length)throw new Error(`ไม่พบไฟล์ในบัญชีหลัก: ${missing.join(', ')}`);const noPackage=apps.filter(x=>!x.packageName).map(x=>x.label);if(noPackage.length)throw new Error(`ไฟล์ไม่มี Package Name: ${noPackage.join(', ')}`);return apps}
function taskIdFrom(res){const x=Array.isArray(res.data)?res.data[0]:res.data;return x?.taskId||null}
async function waitTask(account,path,taskIds,timeout=12*60*1000){if(!taskIds.length)return;const started=Date.now();while(Date.now()-started<timeout){if(state.cancelQueue)throw new Error('ผู้ใช้หยุดคิว');const res=await api(account,path,{taskIds}),rows=Array.isArray(res.data)?res.data:[];if(rows.length){const failed=rows.find(x=>Number(x.taskStatus)<0);if(failed)throw new Error(failed.errorMsg||failed.taskResult||`งานล้มเหลว (${failed.taskStatus})`);if(rows.every(x=>Number(x.taskStatus)===3))return}await sleep(8000)}throw new Error('รอสถานะงานเกิน 12 นาที')}
async function waitDeviceReady(account,padCode){for(let i=0;i<72;i++){if(state.cancelQueue)throw new Error('ผู้ใช้หยุดคิว');try{const res=await api(account,AUTO_PATHS.installed,{padCodes:[padCode],appName:null}),rows=Array.isArray(res.data)?res.data:[];if(rows.some(x=>x.padCode===padCode)||rows.length)return}catch{}await sleep(10000)}throw new Error('เครื่องไม่พร้อมใช้งานภายใน 12 นาที')}
async function installThreeApps(job,apps){const {account,device}=job,padCode=device.padCode;$('#apiState').textContent=`กำลังติดตั้งแอป · ${padCode}`;const taskIds=[];if(account.id==='account-1'){const res=await api(account,AUTO_PATHS.install,{apps:apps.map(x=>({appId:x.fileId,appName:x.appName,pkgName:x.packageName,isGrantAllPerm:true,padCodes:[padCode]}))});for(const x of(Array.isArray(res.data)?res.data:[]))if(x.taskId)taskIds.push(x.taskId)}else{for(const app of apps){if(state.cancelQueue)throw new Error('ผู้ใช้หยุดคิว');const res=await api(account,AUTO_PATHS.uploadInstall,{padCodes:[padCode],autoInstall:1,url:app.downloadUrl,fileName:app.appName,packageName:app.packageName,isAuthorization:true});const id=taskIdFrom(res);if(id)taskIds.push(id);await sleep(500)}}if(taskIds.length)await waitTask(account,AUTO_PATHS.fileTask,taskIds,12*60*1000);log('ติดตั้งแอปอัตโนมัติสำเร็จ',`${padCode} · ${apps.map(x=>x.label).join(', ')}`)}
async function finishReplaceJob(job,apps,progress){const {account,device,taskId}=job;try{$('#apiState').textContent=`รอเครื่องพร้อม · ${device.padCode}`;if(taskId)await waitTask(account,AUTO_PATHS.task,[taskId]);await sleep(8000);await waitDeviceReady(account,device.padCode);await installThreeApps(job,apps);progress.ok++}catch(e){progress.fail++;log(`ติดตั้งอัตโนมัติ ${device.padCode} ไม่สำเร็จ`,e.message,'error')}progress.done++;$('#apiState').textContent=`ติดตั้งแอปแล้ว ${progress.done}/${progress.total}`}
async function runInstallWorkers(jobs,apps){const progress={done:0,total:jobs.length,ok:0,fail:0};let cursor=0;async function worker(){while(cursor<jobs.length&&!state.cancelQueue){const job=jobs[cursor++];await finishReplaceJob(job,apps,progress)}}await Promise.all(Array.from({length:Math.min(3,jobs.length)},worker));return progress}

runBulk=async function(action,extra){const devices=selectedDevices(),groups=Object.groupBy?Object.groupBy(devices,d=>d.accountId):devices.reduce((o,d)=>((o[d.accountId]||=[]).push(d),o),{}),path=PATHS[action];let ok=0,fail=0,stopped=false,jobs=[],apps=null;if(action==='replace'&&autoInstallEnabled()){try{$('#apiState').textContent='กำลังตรวจไฟล์แอป...';apps=await getAutoApps();log('ตรวจไฟล์แอปสำเร็จ',apps.map(x=>x.label).join(', '))}catch(e){$('#apiState').textContent='เชื่อมต่อแล้ว';toast(e.message,'error');log('ยกเลิกเปลี่ยนเครื่อง',e.message,'error');return}}if(action==='replace'){state.queueRunning=true;state.cancelQueue=false;$('#cancelQueue').classList.remove('hidden');$('#clearSelection').classList.add('hidden');let consecutiveFails=0;for(let i=0;i<devices.length;i++){if(state.cancelQueue){stopped=true;break}const d=devices[i],a=ACCOUNTS.find(x=>x.id===d.accountId);$('#apiState').textContent=`ส่งคำสั่งเปลี่ยน ${i+1}/${devices.length}`;try{const res=await api(a,path,{padCodes:[d.padCode],countryCode:'SG',wipeData:true,...extra}),task=Array.isArray(res.data)?res.data[0]:res.data;if(task?.taskStatus===-1)throw new Error('มีคำสั่งเดิมกำลังทำงานอยู่');ok++;consecutiveFails=0;jobs.push({device:d,account:a,taskId:task?.taskId||null});log('ส่งคำสั่งเปลี่ยนเครื่องสำเร็จ',`${d.padCode} · ${a.name}`)}catch(e){fail++;consecutiveFails++;log(`เปลี่ยนเครื่อง ${d.padCode} ไม่สำเร็จ`,e.message,'error');if(consecutiveFails>=2){stopped=true;log('หยุดคิวอัตโนมัติ','เปลี่ยนเครื่องไม่สำเร็จติดต่อกัน 2 เครื่อง','error');break}}if(i<devices.length-1)await sleep(450)}if(apps&&jobs.length&&!state.cancelQueue){const installed=await runInstallWorkers(jobs,apps);toast(`ติดตั้งแอปสำเร็จ ${installed.ok}/${installed.total}${installed.fail?` · ล้มเหลว ${installed.fail}`:''}`,installed.fail?'error':'success')}state.queueRunning=false;$('#cancelQueue').classList.add('hidden');$('#clearSelection').classList.remove('hidden')}else{for(const[id,list]of Object.entries(groups))try{await api(ACCOUNTS.find(a=>a.id===id),path,{padCodes:list.map(d=>d.padCode),...extra});ok+=list.length;log(`${action} สำเร็จ`,`${list.length} เครื่อง · ${ACCOUNTS.find(a=>a.id===id).name}`)}catch(e){fail+=list.length;log(`${action} ไม่สำเร็จ`,e.message,'error')}}if(action==='replace'&&ok){const q=quota();localStorage.setItem('vmos-replace-quota',JSON.stringify({day:q.day,used:q.used+ok}))}$('#apiState').textContent='เชื่อมต่อแล้ว';toast(`${stopped?'หยุดคิวแล้ว · ':''}เปลี่ยนสำเร็จ ${ok} เครื่อง${fail?` · ไม่สำเร็จ ${fail}`:''}`,fail||stopped?'error':'success');clearSelection();renderQuota();setTimeout(refresh,1800)};

const autoBox=document.createElement('div');autoBox.className='warning-box';autoBox.style.cssText='background:#0a2730;color:#b9eef5;border-color:#175061';autoBox.innerHTML=`<label style="display:flex;gap:10px;align-items:flex-start;cursor:pointer"><input id="autoInstallToggle" type="checkbox" ${autoInstallEnabled()?'checked':''} style="margin-top:3px"><span><b>ติดตั้งแอปอัตโนมัติหลังเปลี่ยนเครื่อง</b><br><small>app-debug, grab และ shopee v3-53-31 จากคลังไฟล์บัญชีหลัก</small></span></label>`;$('#settingsAccounts').after(autoBox);$('#autoInstallToggle').onchange=e=>{localStorage.setItem('vmos-auto-install',String(e.target.checked));toast(e.target.checked?'เปิดติดตั้งอัตโนมัติแล้ว':'ปิดติดตั้งอัตโนมัติแล้ว')};
